#!/bin/perl -w
#while (defined($line = <STDIN>)){
#    print "I saw $line";
#}
#while(<STDIN>){
#    print "I saw $_";
#}
#while (defined($line = <>)){
#    chomp($line);
#    print "It was $line that I saw!\n";
#}
#print "@ARGV\n";
#print "$ARGV[1]\n";
#while(<>){
#    chomp;
#    print "It was $_ that I saw!\n";
#}
#while (@array = <STDIN>){
#    print @array;
#    print "@array";
#}
$user = Sam;
$days_to_die = 10;
printf "Hello, %s; your password expires in %d days!\n",$user,$days_to_die;

my @items = qw/wilma dino pebbles/;
my $format = "The items are:\n".("%10s\n" x @items);
## print "the format is>>$format<<\n"; #For debugging
printf $format,@items;

#y $success = open LOG,">>logfile";
#f(!$success){
#   #when open failed
#   #die "Open logfile failed:$!"; #$! means to print the msg generated by system
#   print "Open logfile failed!\n";
#
#print "Test, this should not be printed!\n";
print $0;

#@ARGV = reverse @ARGV;
#print "\n";
#@a = reverse <>;
#print @a;

#print "\n";
#print strings as 20 words flush right
#@str = <STDIN>;
#while($i != 5){
#    foreach(0..9){
#        print;
#	}
#    $i++;
#    }
#print "\n";
#foreach(@str){
#    printf "%21s",$_;
#    }

print "\n";
@str = <STDIN>;
$num = shift @str;
$i = 0;
#print $num/10;
#print "\n";
while($i ne $num/10+1){
    foreach(0..9){
        print; #Same with print $_
	}
    $i++;
    }
print "\n";
#print "$num";
#chomp $num;
$conv = "%".++$num."s";
foreach(@str){
    printf $conv,$_;
    }
